---

name: Audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    -
      uses: actions/checkout@v3
    -
      uses: azure/setup-helm@v3
      with:
        version: v3.6.3
    -
      name: Lint chart
      run: helm lint
